### ISSUE TITLE
Bug: Changing hotkey assignment breaks multiline toggle

### ISSUE THREAD

**Issue by davecan** [argenos/hotkeysplus-obsidian#17]
Hi, thanks for the very helpful plugin. One thing I noticed though is it the ability to handle multiple lines (at least in the bullet toggle hotkey) changes after I rebind the key in the Hotkey settings pane. After I change the hotkey (in my case, to `Ctrl-B` instead of `Cmd-Shift-M`) and select multiple lines and press the `Ctrl-B` hotkey it only toggles the *first* line, not all the selected lines. 

If I change the hotkey back to the default then it returns to the original multiline toggle behavior.

This is unexpected behavior so I'm assuming it's a bug?

Thanks.

**Comment by argenos** [comment]
This is strange. Is it possible there is another hotkey interfering with the hotkey you set?

**Comment by davecan** [comment]
Negative. I just reviewed all of the hotkeys in Obsidian.

Investigating further, it looks like it is a hotkey setting outside of
Obsidian but I can't find it. Somehow Ctrl+B is mapped to move the cursor
left and Ctrl+F is mapped to move the cursor right. I've never seen this
set anywhere and never heard of this but it happens in any app not just
Obsidian. So it appears Obsidian detects the hotkey but before it can fire
the cursor is moved left which causes it to (a) deselect the lines and (b)
only be present on the top line of the selection by the time the plugin
command is executed. But I can't find any definition of those mappings
anywhere. It's driving me crazy.

Still, it appears this is somehow a PEBKAC and not an issue with the plugin
after all. Sorry about that!
