### ISSUE TITLE
Feature Request: Toggle Readable Line Width

### ISSUE THREAD

**Issue by eleanorkonik** [argenos/hotkeysplus-obsidian#21]
It would be really nice if I could toggle between readable line width and not readable line width, thaaanks! Mostly I like readable line width on but sometimes with a big table or dataview or something it's a pain :<

**Comment by FelipeRearden** [comment]
+1 for this request!

I'm imagining the combination on this hotkey with the [Maximise](https://github.com/deathau/maximise-active-pane-obsidian) plugin from death.au for long reading. 

Would be a game changer for me :)

**Comment by JeppeKlitgaard** [comment]
If this doesn't get picked up here, I'd be happy to implement it in ObsidianTweaks (Sometime next week, most likely)

**Comment by FelipeRearden** [comment]
Hello @argenos and @valentine195 !!!!

Just to let you know that I tried the new command `Toggle Readable Line Length` on a new Obsidian Vault (no themes and no snippets) and in my test: 
- the command changes the toggle behavior in the settings (ON -> OFF and OFF -> ON) 
- but there is no result in the screen (active note) when compared to the manual toggle action. Both on Editor and Preview Mode

Version `0.2.7`
Obsidian `0.12.19`
Windows 7

Thanks for this feature @valentine195 !!!!

**Comment by argenos** [comment]
@FelipeRearden I gave it a try yesterday, and it was working fine for me (Editing view, LP mode on Obsidian 0.13.X). What versions of Obsidian are you using (Installer, is it also 0.12.9)? Could this be a theme issue?

**Comment by FelipeRearden** [comment]
> @FelipeRearden I gave it a try yesterday, and it was working fine for me (Editing view, LP mode on Obsidian 0.13.X). What versions of Obsidian are you using (Installer, is it also 0.12.9)? Could this be a theme issue? 

Thanks for your replay @argenos !

My installer version is `0.12.15` and it's clean vault without themes and snippets 

I'm gonna create a new vault with the `0.12.19` version installer and I get back to you in a few minutes :)

**Comment by FelipeRearden** [comment]
> I'm gonna create a new vault with the 0.12.19 version installer and I get back to you in a few minutes :)

Same behavior on `0.12.19` with the `0.12.19` installer :(

it's okay ! I'm gonna wait for the next public release since it's working in the latest insider build `0.13.7`

When I update I will command again in this post !

Thanks for your help @argenos and thanks @valentine195 for this command. It's something that I really was looking for. 

Have a great day :)

**Comment by valentine195** [comment]
Never would’ve thought this behavior would change between 0.12.X and 0.13.X, sorry about that!

**Comment by FelipeRearden** [comment]
> Never would’ve thought this behavior would change between 0.12.X and 0.13.X, sorry about that!

No problem at all @valentine195 !!!!! 😍 😍 😍 😍 😍 😍 

It is just a matter of more weeks until now. We can wait :)

I'm so happy that I could have this command. Thank you very much for making this happen to us !


Have a great day!

**Comment by FelipeRearden** [comment]
Hello @argenos and @valentine195 !!!!

Working perfect on Obsidian `0.13.14`
- reading mode
- live preview
- editor (legacy mode)

Thank you very much !!!!!!!!!!
