### ISSUE TITLE
Hot key ⇧⌘M not working for me on Mac

### ISSUE THREAD

**Issue by swehba** [argenos/hotkeysplus-obsidian#24]
I have this key mapped as follows:

[screenshot](https://d.pr/i/veTJ7l+)

It used to work just fine, but now it does nothing. Has something changed in the plugin? Is there a possible conflict with some other plugin? I check other key-mapping apps I use (e.g., Keyboard Maestro) and they do not map that key combination. And, as I mentioned, it used to work just fine. Restarting Obsidian does not help.

**Comment by argenos** [comment]
Nothing has changed on my side, and I can't seem to reproduce. It might indeed be something Mac-specific. Have you tried setting a different key combination?

**Comment by swehba** [comment]
Problem found. I had another app open — Capto — which mapped ⇧⌘M. It was stealing the keystrokes away from HotKeys. Thanks, and sorry for the false alarm. Also thank for the nice plugin. ;-)
