### ISSUE TITLE
Feature Request: "Duplicate current line *up*" in addition to "Duplicate current line *down*"

### ISSUE THREAD

**Issue by tzarick** [argenos/hotkeysplus-obsidian#25]
It would be great to be able to duplicate lines up in addition to down. The "Duplicate current line or selected lines" feature effectively duplicates the line down currently, which is great, but it would be nice to have the option to go both directions. I imagine this being analogous to using the `Alt+Shift+up_arrow` and `Alt+Shift+down_arrow` hotkeys in VSCode. This includes the cursor being placed on the new line with the duplicated content (the same way the down feature already works now).

The proposal here is to add support for a new option called "Duplicate the current line or selected lines up" and also rename the current duplication feature to "Duplicate the current line or selected lines down."

If this is something that you think would be a good addition and would like to action, and are looking for help, I'd be more than happy to look into creating a PR around this.

**Comment by argenos** [comment]
I'll mention @NomarCub who introduced this feature, otherwise happy to accept PRs.

**Comment by NomarCub** [comment]
Would be a nice addition, I didn't even know VSCode had that. It's called `Copy Line Up` and down, we could also use that name.
Your help is welcome.
