### ISSUE TITLE
Cursor incorrectly placed when using header shortcut

### ISSUE THREAD

**Issue by gabrielwhite** [argenos/hotkeysplus-obsidian#31]
I created a shortcut CMD-1 to create an L1 heading.

I upgraded to 0.13.14 yesterday and when I use this shortcut the cursor is placed to the **left** of the inserted "#" rather than to the right. So, I need to move the cursor and then start typing.

I would expect the cursor to be placed to the right of the inserted MD code.

I'm on MacOS.

Thanks!

**Comment by argenos** [comment]
Hi @gabrielwhite, are you sure this is the right repo? We haven't added any commands for headers to this plugin:
![image](https://user-images.githubusercontent.com/5426039/147822571-c68da68a-352b-4a5e-8636-ffa1dc6e388e.png)

**Comment by gabrielwhite** [comment]
Wrong repo sorry!
