### ISSUE TITLE
Feature Request: Move Between Split Panes

### ISSUE THREAD

**Issue by Threeinone** [argenos/hotkeysplus-obsidian#40]
Currently in Obsidian, there are hotkeys to split tabs into different panes, but no hotkey to switch between panes. Adding this functionality would be useful for people who prefer not to use the mouse as much as possible.

this could be implemented similar to Vim or tmux, where the hotkeys move between panes spacially (move to right, left, up or down pane since you can split multiple times) instead of the VS code implementation which uses numbers to switch.

**Comment by FelipeRearden** [comment]
Hello @Threeinone !!!

Trying to help here ...

There are two plugins to help with this

→ [Pane Relief](https://github.com/pjeby/pane-relief)

→ [Cycle Through Panes](https://github.com/phibr0/cycle-through-panes)


I hope it helps 🙏

**Comment by kbdragon** [comment]
For anyone reading this looking for a solution, you can set up hotkeys to switch between different tab groups.
![image](https://github.com/argenos/hotkeysplus-obsidian/assets/113253861/96b2475c-b976-4fe5-8299-c7fb4cdf2f44)

**Comment by argenos** [comment]
Please use one of the alternatives mentioned above
