### ISSUE TITLE
FR: [[name]] <-> name![[name]] 

### ISSUE THREAD

**Issue by anatoliibakhtin** [argenos/hotkeysplus-obsidian#41]
@lynchjames Hi, thanks for implementing the hotkey, it's one I use a lot! But not always in the way I would like:

When I use this function [Toggle embeds for internal links](https://github.com/argenos/hotkeysplus-obsidian#hotkeysplus-obsidian) with a list, my list looks crooked (it's because obsidian doesn't display the embedded file name):
![image](https://github.com/argenos/hotkeysplus-obsidian/assets/71871141/d6e8e87e-76b0-4914-a45c-aaeee9642940)

It would be nice to have a hotkey to automatically add-delete the name of the ![[open]]-[[closed]] file, so that the embedded lists are displayed correctly.

Could you add this feature as another hotkey or is it better to write to obsidian developers?

Thank you for your attention ! 🌳

**Comment by argenos** [comment]
Sorry for the late reply. I'm afraid that this is a very specific use case/preference, so I won't accept any PRs on this.
