### ISSUE TITLE
Feature request: hotkey to select & insert a template in a note

### ISSUE THREAD

**Issue by afokapu** [argenos/hotkeysplus-obsidian#5]
Hi Argenos, awesome work.

# Problem
I have 10 templates among which 3 that I use a regurlaly (more than 10x a day for meeting notes). 

# Current behavior to insert template using hotkey
1 - Ctrl + Shift + T: open template list
2 - Select template with keyboard or mouse
3 - Template is inserted in note

# Expected behavior to insert template using hotkey
1 - Ctrl + Shift + (0-9): insert the template bonded to a number (0-9)

Each template would have a number assigned to it (up to 10 templates)

Best

**Comment by TonyCr46** [comment]
I think this might  be what you are getting at. I was just watching [Bryan Jenks' video](https://youtu.be/1eUxQo6Dy7k) on YouTube about using templates. At about [here](https://youtu.be/1eUxQo6Dy7k?t=165), he talks about using a hotkey he set up (Cmd - Shift - I) to bring up a menu of his templates and then insert one of them. Problem is, he doesn't say how to create the hotkey and I'm too new to Obsidian to know how to do it. If anybody knows (or can figure it out), I'd like to know.

Thanks.

Tony

**Comment by mambocab** [comment]
@TonyCr46 Open settings, then go to `Hotkeys` and search for `Insert template`. From there you can set it to whatever you like.

I understand if this is out of scope for this plugin, but I'd absolutely use this feature.

**Comment by TonyCr46** [comment]
@mambocab Thanks for that. I will give it a try.

**Comment by Vinzent03** [comment]
@argenos I am working on this implementation. To set hotkeys for selected files, it would be needed to set them in a settings pane. Would that be too much for this plugin and I put this in an extra external plugin or is it okay?

**Comment by argenos** [comment]
@Vinzent03 I could have sworn I there was a plugin already doing this, but I must have dreamt this. Maybe I''m thinking of your starred files plugin. In any case, I think a standalone plugin for inserting templates makes sense and allows for more features around templates to be added in the future.

**Comment by Vinzent03** [comment]
I agree with you. Makes it easier to find this feature in the Obsidian marketplace too.

**Comment by Vinzent03** [comment]
My new plugin is not available: https://github.com/Vinzent03/obsidian-hotkeys-for-templates This should fit the author's needs and the issue can be closed.

**Comment by argenos** [comment]
Thank you, @Vinzent03!
