### ISSUE TITLE
【bug】About order list

### ISSUE THREAD

**Issue by OrdinaryYZH** [argenos/hotkeysplus-obsidian#6]
Thank you for your plugin~

My Obsidian version is 0.9.11;
os: windows 10

When I used ctrl + shift + m to convert texts to ordered list, the lists were all 1：

![image](https://user-images.githubusercontent.com/10287222/99261316-7ed3af00-2857-11eb-982d-a5488eaa41a6.png)

And when I change the hot key to other key, 

![image](https://user-images.githubusercontent.com/10287222/99262024-6e700400-2858-11eb-809b-558527778187.png)

had another problem, it did't work well, appeared the under problem:

![image](https://user-images.githubusercontent.com/10287222/99262212-a7a87400-2858-11eb-9809-92683ce1a03a.png)

**Comment by argenos** [comment]
@OrdinaryYZH The first one isn't really a bug, but more of a hardcoded assumption. In markdown all elements can use the `1. ` and in preview mode, the list will be rendered correctly. 

Regarding the 2nd bug, could you please provide steps to reproduce it?

**Comment by OrdinaryYZH** [comment]
> @OrdinaryYZH The first one isn't really a bug, but more of a hardcoded assumption. In markdown all elements can use the `1. ` and in preview mode, the list will be rendered correctly.
> 
> Regarding the 2nd bug, could you please provide steps to reproduce it?

Yes, I know the fist one can rendered correctly, but I want to see the "correct" number in edit mode :-P 

And the second, my steps are:
1. change the hotkey in options, e.g. ctrl + [
2. choose multi lines and put ctrl + [ more than one

Then the problem show up

**Comment by argenos** [comment]
@OrdinaryYZH, unfortunately, I can't reproduce your second bug due to my keyboard layout

Regarding the first issue, I'm afraid I can't invest more time making the ordered lists smarter, that would require knowing if the line above also contains a list element, and also consider the indentation of all selected elements (which I'll be honest, is not smart either). Feel free to open a PR for it though!

**Comment by OrdinaryYZH** [comment]
Ok, thank you for reply~
