### ISSUE TITLE
Wrong check box level generation

### ISSUE THREAD

**Issue by wenlzhang** [argenos/hotkeysplus-obsidian#7]
Before updating to macOS Big Sur, the check box can be generated correctly for any level of unnumbered lists. However, after updating macOS, this does not work for me any more.

Before using the hotkeys:

- Level 1
  - Level 2

After using the hotkeys:

- Level 1
- [x] - [x] Level 2 (as can be seen, there is an extra "- [x]" here)

**Comment by lastobelus** [comment]
I am also experiencing this bug, but I _haven't_ updated to Big Sur.

**Comment by argenos** [comment]
I'm not sure what was causing this issue, but I've just released 0.2.5 with some fixes for the regex, which should help with this. Let me know if this fixes it or if you're still seeing the issue!

**Comment by wenlzhang** [comment]
Great! It's working for me now.
